#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "emcc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -mandroid -I/include -B/lib -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "android"
  #define DATE "Mon Dec 22 04:33:27 EST 2014"
#endif
